import { useState, useEffect } from "react";
import { motion } from "framer-motion";
import {
  Robot,
  PaperPlaneTilt,
  Sparkle,
  Lightning,
  Code,
} from "@phosphor-icons/react";

// Example prompts for the AI assistant
const examplePrompts = [
  "Generate a failover policy for my GPT-4 endpoints",
  "Create an alert rule for response time > 2 seconds",
  "Set up weekly drift reports for the legal team",
  "Configure multi-region redundancy for Anthropic",
];

// Simulated AI-generated policy code
const generatedCode = `// Generated by Cognitude AI Assistant
import { Policy, Failover, Alert } from '@cognitude/sdk';

export const gpt4FailoverPolicy = new Policy({
  name: "gpt4-production-failover",
  
  // Primary endpoint with fallbacks
  endpoints: [
    { provider: "openai", model: "gpt-4-turbo" },
    { provider: "anthropic", model: "claude-3-opus" },
    { provider: "google", model: "gemini-pro" }
  ],
  
  // Automatic failover triggers
  failover: new Failover({
    triggers: {
      latencyMs: 3000,
      errorRate: 0.05,
      driftScore: 0.15
    },
    strategy: "least-latency",
    cooldownMs: 60000
  }),
  
  // Real-time alerting
  alerts: new Alert({
    channels: ["slack:#ai-ops", "pagerduty"],
    severity: "high"
  })
});`;

function AIAssistant() {
  const [inputValue, setInputValue] = useState("");
  const [isTyping, setIsTyping] = useState(false);
  const [displayedCode, setDisplayedCode] = useState("");
  const [showCode, setShowCode] = useState(false);
  const [currentPrompt, setCurrentPrompt] = useState(examplePrompts[0]);

  // Typing animation for the code
  useEffect(() => {
    if (showCode && displayedCode.length < generatedCode.length) {
      const timer = setTimeout(() => {
        setDisplayedCode(generatedCode.slice(0, displayedCode.length + 3));
      }, 15);
      return () => clearTimeout(timer);
    }
  }, [showCode, displayedCode]);

  const handleSubmit = (e) => {
    e.preventDefault();
    if (!inputValue.trim()) return;

    setIsTyping(true);
    setTimeout(() => {
      setIsTyping(false);
      setShowCode(true);
      setDisplayedCode("");
    }, 1500);
  };

  const handleExampleClick = (prompt) => {
    setInputValue(prompt);
    setCurrentPrompt(prompt);
    setShowCode(false);
    setDisplayedCode("");
  };

  return (
    <section className="relative py-24 bg-gradient-to-b from-slate-950 to-slate-900 overflow-hidden">
      {/* Background elements */}
      <div className="absolute inset-0 bg-[linear-gradient(to_right,#1e293b_1px,transparent_1px),linear-gradient(to_bottom,#1e293b_1px,transparent_1px)] bg-[size:4rem_4rem] opacity-20" />

      {/* Gradient orbs */}
      <div className="absolute top-1/4 right-1/4 w-96 h-96 bg-purple-500/10 rounded-full blur-3xl" />
      <div className="absolute bottom-1/4 left-1/4 w-96 h-96 bg-emerald-500/10 rounded-full blur-3xl" />

      <div className="relative max-w-6xl mx-auto px-4 sm:px-6">
        {/* Header */}
        <motion.div
          className="text-center mb-12"
          initial={{ opacity: 0, y: 20 }}
          whileInView={{ opacity: 1, y: 0 }}
          viewport={{ once: true }}
          transition={{ duration: 0.6 }}
        >
          <div className="inline-flex items-center gap-2 rounded-full border border-emerald-500/30 bg-emerald-500/10 px-4 py-1.5 mb-6">
            <Sparkle className="w-4 h-4 text-emerald-400" />
            <span className="text-sm font-medium text-emerald-300">
              AI-Powered Configuration
            </span>
          </div>

          <h2 className="text-4xl md:text-5xl font-bold text-white mb-4">
            Describe your policy.{" "}
            <span className="bg-gradient-to-r from-emerald-400 via-purple-400 to-emerald-400 bg-clip-text text-transparent">
              We'll generate the code.
            </span>
          </h2>

          <p className="text-lg text-slate-400 max-w-2xl mx-auto">
            Our AI assistant understands your stability requirements and
            generates production-ready policy code in seconds.
          </p>
        </motion.div>

        {/* AI Chat Interface */}
        <motion.div
          className="relative max-w-4xl mx-auto"
          initial={{ opacity: 0, y: 20 }}
          whileInView={{ opacity: 1, y: 0 }}
          viewport={{ once: true }}
          transition={{ duration: 0.6, delay: 0.2 }}
        >
          {/* Glow effect */}
          <div className="absolute -inset-4 bg-gradient-to-r from-purple-500/20 via-emerald-500/20 to-purple-500/20 rounded-3xl blur-2xl opacity-50" />

          {/* Chat container */}
          <div className="relative rounded-2xl overflow-hidden border border-slate-700/50 bg-slate-900/90 backdrop-blur-xl shadow-2xl">
            {/* Header */}
            <div className="flex items-center justify-between px-6 py-4 bg-slate-800/80 border-b border-slate-700/50">
              <div className="flex items-center gap-3">
                <div className="w-10 h-10 rounded-xl bg-gradient-to-br from-purple-500 to-emerald-500 flex items-center justify-center">
                  <Robot className="w-5 h-5 text-white" weight="fill" />
                </div>
                <div>
                  <h3 className="font-semibold text-white">
                    Cognitude Assistant
                  </h3>
                  <p className="text-xs text-slate-400">
                    v2.1 • Policy Generator
                  </p>
                </div>
              </div>
              <div className="flex items-center gap-2 px-3 py-1 rounded-full bg-emerald-500/20 border border-emerald-500/30">
                <div className="w-2 h-2 rounded-full bg-emerald-500 animate-pulse" />
                <span className="text-xs text-emerald-400 font-medium">
                  Online
                </span>
              </div>
            </div>

            {/* Chat area */}
            <div className="p-6 space-y-6 min-h-[400px]">
              {/* Example prompts */}
              {!showCode && !isTyping && (
                <div className="space-y-3">
                  <p className="text-sm text-slate-500">Try an example:</p>
                  <div className="flex flex-wrap gap-2">
                    {examplePrompts.map((prompt, i) => (
                      <button
                        key={i}
                        onClick={() => handleExampleClick(prompt)}
                        className={`px-3 py-1.5 rounded-lg text-sm transition-all ${
                          inputValue === prompt
                            ? "bg-purple-500/20 border border-purple-500/50 text-purple-300"
                            : "bg-slate-800 border border-slate-700 text-slate-400 hover:border-slate-600 hover:text-slate-300"
                        }`}
                      >
                        {prompt}
                      </button>
                    ))}
                  </div>
                </div>
              )}

              {/* Typing indicator */}
              {isTyping && (
                <motion.div
                  initial={{ opacity: 0, y: 10 }}
                  animate={{ opacity: 1, y: 0 }}
                  className="flex items-center gap-3"
                >
                  <div className="w-8 h-8 rounded-lg bg-gradient-to-br from-purple-500 to-emerald-500 flex items-center justify-center">
                    <Robot className="w-4 h-4 text-white" weight="fill" />
                  </div>
                  <div className="flex gap-1 px-4 py-3 rounded-xl bg-slate-800">
                    <div
                      className="w-2 h-2 rounded-full bg-slate-500 animate-bounce"
                      style={{ animationDelay: "0ms" }}
                    />
                    <div
                      className="w-2 h-2 rounded-full bg-slate-500 animate-bounce"
                      style={{ animationDelay: "150ms" }}
                    />
                    <div
                      className="w-2 h-2 rounded-full bg-slate-500 animate-bounce"
                      style={{ animationDelay: "300ms" }}
                    />
                  </div>
                </motion.div>
              )}

              {/* Generated code */}
              {showCode && (
                <motion.div
                  initial={{ opacity: 0, y: 10 }}
                  animate={{ opacity: 1, y: 0 }}
                  className="space-y-4"
                >
                  {/* User message */}
                  <div className="flex justify-end">
                    <div className="max-w-md px-4 py-3 rounded-xl bg-purple-500/20 border border-purple-500/30">
                      <p className="text-sm text-purple-200">{currentPrompt}</p>
                    </div>
                  </div>

                  {/* AI response */}
                  <div className="flex items-start gap-3">
                    <div className="w-8 h-8 rounded-lg bg-gradient-to-br from-purple-500 to-emerald-500 flex items-center justify-center flex-shrink-0">
                      <Robot className="w-4 h-4 text-white" weight="fill" />
                    </div>
                    <div className="flex-1 space-y-3">
                      <div className="flex items-center gap-2">
                        <Lightning className="w-4 h-4 text-emerald-400" />
                        <span className="text-sm text-emerald-400">
                          Generated policy for your endpoint
                        </span>
                      </div>

                      {/* Code block */}
                      <div className="rounded-xl overflow-hidden border border-slate-700/50 bg-slate-950">
                        <div className="flex items-center justify-between px-4 py-2 bg-slate-800/50 border-b border-slate-700/50">
                          <div className="flex items-center gap-2">
                            <Code className="w-4 h-4 text-slate-400" />
                            <span className="text-xs text-slate-400 font-mono">
                              gpt4-failover.policy.ts
                            </span>
                          </div>
                          <span className="text-xs text-emerald-400">
                            ✓ Valid TypeScript
                          </span>
                        </div>
                        <pre className="p-4 text-sm font-mono text-slate-300 overflow-x-auto max-h-[300px]">
                          {displayedCode}
                          <span className="animate-pulse text-purple-400">
                            |
                          </span>
                        </pre>
                      </div>

                      {/* Action buttons */}
                      {displayedCode.length === generatedCode.length && (
                        <motion.div
                          initial={{ opacity: 0, y: 10 }}
                          animate={{ opacity: 1, y: 0 }}
                          className="flex gap-2"
                        >
                          <button className="px-4 py-2 rounded-lg bg-purple-500 text-white text-sm font-medium hover:bg-purple-600 transition-colors">
                            Deploy Policy
                          </button>
                          <button className="px-4 py-2 rounded-lg bg-slate-800 text-slate-300 text-sm font-medium hover:bg-slate-700 transition-colors">
                            Edit in IDE
                          </button>
                          <button className="px-4 py-2 rounded-lg bg-slate-800 text-slate-300 text-sm font-medium hover:bg-slate-700 transition-colors">
                            Copy Code
                          </button>
                        </motion.div>
                      )}
                    </div>
                  </div>
                </motion.div>
              )}
            </div>

            {/* Input area */}
            <form
              onSubmit={handleSubmit}
              className="p-4 bg-slate-800/50 border-t border-slate-700/50"
            >
              <div className="flex gap-3">
                <input
                  type="text"
                  value={inputValue}
                  onChange={(e) => setInputValue(e.target.value)}
                  placeholder="Describe the policy you want to create..."
                  className="flex-1 px-4 py-3 rounded-xl bg-slate-900 border border-slate-700 text-white placeholder:text-slate-500 focus:outline-none focus:border-purple-500/50 focus:ring-2 focus:ring-purple-500/20 transition-all"
                />
                <button
                  type="submit"
                  disabled={!inputValue.trim() || isTyping}
                  className="px-6 py-3 rounded-xl bg-gradient-to-r from-purple-500 to-emerald-500 text-white font-medium hover:shadow-lg hover:shadow-purple-500/25 transition-all disabled:opacity-50 disabled:cursor-not-allowed"
                >
                  <PaperPlaneTilt className="w-5 h-5" weight="fill" />
                </button>
              </div>
            </form>
          </div>

          {/* Floating feature badges */}
          <motion.div
            className="absolute -left-8 top-1/4 px-3 py-2 rounded-lg bg-slate-800/90 border border-slate-700 shadow-xl hidden lg:block"
            initial={{ opacity: 0, x: -20 }}
            whileInView={{ opacity: 1, x: 0 }}
            viewport={{ once: true }}
            transition={{ duration: 0.4, delay: 0.5 }}
          >
            <div className="flex items-center gap-2">
              <Sparkle className="w-4 h-4 text-purple-400" />
              <span className="text-xs text-slate-400">GPT-4 Turbo</span>
            </div>
          </motion.div>

          <motion.div
            className="absolute -right-8 bottom-1/3 px-3 py-2 rounded-lg bg-slate-800/90 border border-slate-700 shadow-xl hidden lg:block"
            initial={{ opacity: 0, x: 20 }}
            whileInView={{ opacity: 1, x: 0 }}
            viewport={{ once: true }}
            transition={{ duration: 0.4, delay: 0.6 }}
          >
            <div className="flex items-center gap-2">
              <Lightning className="w-4 h-4 text-emerald-400" />
              <span className="text-xs text-slate-400">Instant generation</span>
            </div>
          </motion.div>
        </motion.div>

        {/* Bottom stats */}
        <motion.div
          className="mt-16 text-center"
          initial={{ opacity: 0, y: 20 }}
          whileInView={{ opacity: 1, y: 0 }}
          viewport={{ once: true }}
          transition={{ duration: 0.6, delay: 0.4 }}
        >
          <p className="text-slate-500 text-sm">
            Our AI has generated over{" "}
            <span className="text-white font-semibold">10,000+</span> policies
            for teams at leading companies
          </p>
        </motion.div>
      </div>
    </section>
  );
}

export default AIAssistant;
